name: CI

on:
  release:
    types: [ published ]

jobs:
  deploy:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCRIO_USER }}
          password: ${{ secrets.GHCRIO_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t "ghcr.io/neuro-inc/mlflow:${{ github.event.release.tag_name }}" .

      - name: Tag Docker Image for platform-pipelines
        run: |
          docker tag ghcr.io/neuro-inc/mlflow:${{ github.event.release.tag_name }} ghcr.io/neuro-inc/mlflow:pipelines

      - name: Push Docker Image
        run: |
          docker push ghcr.io/neuro-inc/mlflow:${{ github.event.release.tag_name }}
          docker push ghcr.io/neuro-inc/mlflow:pipelines

